# -*- coding: utf-8 -*-
"""World GDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F79TbZlC09iqrQ9q_nGUhIxRtxjDL219
"""

import streamlit as st
import requests
import pandas as pd
import plotly.express as px
from bs4 import BeautifulSoup

# Wikipedia URL
URL = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

# Function to scrape data
@st.cache_data
def fetch_gdp_data():
    response = requests.get(URL)
    soup = BeautifulSoup(response.text, 'html.parser')
    tables = soup.find_all("table", {"class": "wikitable"})

    data_sources = ["IMF", "World Bank", "United Nations"]
    dataframes = {}

    for source in data_sources:
        for table in tables:
            if source in table.text:
                df = pd.read_html(str(table))[0]
                df.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in df.columns]
                relevant_columns = [col for col in df.columns if "Country" in col or source in col]
                df = df[relevant_columns]
                df = df.rename(columns={df.columns[0]: "Country", df.columns[1]: "GDP (Millions USD)"})
                df = df.dropna(subset=["GDP (Millions USD)"])
                df["GDP (Millions USD)"] = df["GDP (Millions USD)"].astype(str).str.replace(',', '').astype(float)
                df = df.dropna(subset=["GDP (Millions USD)"])
                dataframes[source] = df
                break

    return dataframes

# Function to assign continents
def get_continent(country):
    for continent, countries in continent_map.items():
        if country in countries:
            return continent
    return "Other"

# Dictionary mapping countries to continents
continent_map = {
    "Asia": ["China", "India", "Japan", "South Korea", "Indonesia", "Saudi Arabia"],
    "Europe": ["Germany", "United Kingdom", "France", "Italy", "Spain"],
    "North America": ["United States", "Canada", "Mexico"],
    "South America": ["Brazil", "Argentina"],
    "Africa": ["South Africa", "Nigeria", "Egypt"],
    "Oceania": ["Australia", "New Zealand"]
}

# Streamlit UI
st.title("Global GDP Analysis")
st.sidebar.header("Settings")

# Fetch data
gdp_data = fetch_gdp_data()

# User selection for data source
selected_source = st.sidebar.selectbox("Select Data Source", list(gdp_data.keys()))
df = gdp_data[selected_source]

# Assign continent
df["Continent"] = df["Country"].apply(get_continent)

# Aggregate GDP by Continent and Country
df_continent = df.groupby(["Continent", "Country"]).sum().reset_index()

# Plotting stacked bar chart
fig = px.bar(
    df_continent,
    x="Continent",
    y="GDP (Millions USD)",
    color="Country",
    title=f"Nominal GDP by Country and Continent ({selected_source} Data)",
    labels={"GDP (Millions USD)": "GDP (Million USD)"},
    barmode="stack"
)

# Display plot
st.plotly_chart(fig)